YemekSepette/Models/Sube.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace YemekSepette.Models
{
    public class Sube
    {
        public int SubeID { get; set; }

        public int RestoranID { get; set; }

        public int SemtID { get; set; }
        [Display(ResourceType = typeof(Resources.Kullanici.Home), Name = "SubeAdi")]
        public string SubeIsmi { get; set; }

        [Display(ResourceType = typeof(Resources.Kullanici.Home), Name = "Adres")]
        public string AcikAdres { get; set; }

        /* restoran telefonu */
        [Display(ResourceType = typeof(Resources.Kullanici.Home), Name = "Telefon")]
        public string Telefon { get; set; }

        /* restoranin calisma baslangic saati */
        [DisplayFormat(DataFormatString = "{0: HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CalismaBaslangicSaati { get; set; }

        /* restoranin calisma bitis saati */
        [DisplayFormat(DataFormatString = "{0: HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CalismaBitisSaati { get; set; }

        /* ortalama servis suresi (dakika biciminde) */
        [Display(ResourceType = typeof(Resources.Kullanici.Home), Name = "ServisSuresi")]
        public int ServisSuresi { get; set; }

        public virtual Restoran Restoran { get; set; }

        public virtual Semt Semt { get; set; }

        public virtual ICollection<SubeYorum> SubeYorumlari { get; set; }

        public virtual ICollection<Siparis> Siparisler { get; set; }

    }
}

YemekSepette/Areas/Admin/Controllers/SubeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekSepette.DAL;
using YemekSepette.Models;

namespace YemekSepette.Areas.Admin.Controllers
{
    public class SubeController : AdminController
    {
        private YemekSepetteContext db = new YemekSepetteContext();

        // GET: Admin/Sube
        public ActionResult Index(int? page, string currentFiler, string arama, string siralama)
        {
            if (arama != null)
            {
                page = 1;
            }
            else
            {
                arama = currentFiler;
            }
            ViewBag.CurrentFilter = arama;
            ViewBag.SortParam = siralama == "azalan" ? "artan" : "azalan";
            ViewBag.CurrentSort = siralama;

            var subeler = db.Subeler.Include(s => s.Restoran).Include(s => s.Semt).OrderBy(x => x.Restoran.RestoranIsmi).ToList();
            if (siralama == "azalan")
            {
                subeler = db.Subeler.Include(s => s.Restoran).Include(s => s.Semt).OrderByDescending(x => x.Restoran.RestoranIsmi).ToList();
            }

            if (!String.IsNullOrEmpty(arama))
            {
                subeler = subeler.Where(x => x.Restoran.RestoranIsmi.ToUpper().Contains(arama.ToUpper())
                || x.SubeIsmi.ToUpper().Contains(arama.ToUpper()) || x.Semt.SemtAd.ToUpper().Contains(arama.ToUpper())
                || x.Semt.Sehir.SehirAd.ToUpper().Contains(arama.ToUpper())
                ).ToList();
            }

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            ViewBag.SonucSayisi = subeler.Count();
            //var subeler = db.Subeler.Include(s => s.Restoran).Include(s => s.Semt);
            return View(subeler.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Sube/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sube sube = db.Subeler.Find(id);
            if (sube == null)
            {
                return HttpNotFound();
            }
            return View(sube);
        }

        // GET: Admin/Sube/Create
        public ActionResult Create()
        {
            ViewBag.RestoranID = new SelectList(db.Restoranlar, "RestoranID", "RestoranIsmi");
            ViewBag.SemtID = new SelectList(db.Semtler, "SemtID", "SemtAd");
            return View();
        }

        // POST: Admin/Sube/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubeID,RestoranID,SemtID,SubeIsmi,AcikAdres,Telefon,ServisSuresi")] Sube sube)
        {
            if (ModelState.IsValid)
            {
                db.Subeler.Add(sube);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RestoranID = new SelectList(db.Restoranlar, "RestoranID", "RestoranIsmi", sube.RestoranID);
            ViewBag.SemtID = new SelectList(db.Semtler, "SemtID", "SemtAd", sube.SemtID);
            return View(sube);
        }

        // GET: Admin/Sube/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sube sube = db.Subeler.Find(id);
            if (sube == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestoranID = new SelectList(db.Restoranlar, "RestoranID", "RestoranIsmi", sube.RestoranID);
            ViewBag.SemtID = new SelectList(db.Semtler, "SemtID", "SemtAd", sube.SemtID);
            return View(sube);
        }

        // POST: Admin/Sube/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubeID,RestoranID,SemtID,SubeIsmi,AcikAdres,Telefon,ServisSuresi")] Sube sube)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sube).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RestoranID = new SelectList(db.Restoranlar, "RestoranID", "RestoranIsmi", sube.RestoranID);
            ViewBag.SemtID = new SelectList(db.Semtler, "SemtID", "SemtAd", sube.SemtID);
            return View(sube);
        }

        // GET: Admin/Sube/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sube sube = db.Subeler.Find(id);
            if (sube == null)
            {
                return HttpNotFound();
            }
            return View(sube);
        }

        // POST: Admin/Sube/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sube sube = db.Subeler.Find(id);
            db.Subeler.Remove(sube);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekSepette/Areas/Admin/Views/Sube/Create.cshtml
@model YemekSepette.Models.Sube

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sube</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RestoranID, "RestoranID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RestoranID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestoranID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemtID, "SemtID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SemtID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SemtID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubeIsmi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubeIsmi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubeIsmi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcikAdres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcikAdres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcikAdres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServisSuresi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServisSuresi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServisSuresi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekSepette/Areas/Admin/Views/Sube/Delete.cshtml
@model YemekSepette.Models.Sube

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sube</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restoran.RestoranIsmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restoran.RestoranIsmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Semt.SemtAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Semt.SemtAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubeIsmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubeIsmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcikAdres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcikAdres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServisSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServisSuresi)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

YemekSepette/Areas/Admin/Views/Sube/Details.cshtml
@model YemekSepette.Models.Sube

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Sube</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restoran.RestoranIsmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restoran.RestoranIsmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Semt.SemtAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Semt.SemtAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubeIsmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubeIsmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcikAdres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcikAdres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServisSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServisSuresi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

YemekSepette/Areas/Admin/Views/Sube/Edit.cshtml
@model YemekSepette.Models.Sube

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sube</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubeID)

        <div class="form-group">
            @Html.LabelFor(model => model.RestoranID, "RestoranID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RestoranID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestoranID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemtID, "SemtID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SemtID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SemtID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubeIsmi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubeIsmi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubeIsmi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcikAdres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcikAdres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcikAdres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServisSuresi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServisSuresi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServisSuresi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekSepette/Areas/Admin/Views/Sube/Index.cshtml
@model PagedList.IPagedList<YemekSepette.Models.Sube>
@using PagedList.Mvc;

@{
    ViewBag.Title = Resources.Kullanici.Home.Subeler;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.Subeler</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            @using (Html.BeginForm("Index", "Sube", FormMethod.Get))
                            {
                                <div class="input-group">
                                    @Html.TextBox("Arama", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                                    <div class="input-group-btn">
                                        <input type="submit" value="@Resources.Kullanici.Home.Ara" class="btn btn-danger" />
                                    </div>
                                    <!-- /btn-group -->

                                </div>
                            }
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                <thead>
                                    <tr role="row">
                                        <th>
                                            @Html.ActionLink(Resources.Kullanici.Home.Restoran, "Index", new { siralama = ViewBag.SortParam })
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.SubeIsmi
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.Sehir
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.Bolge
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.Telefon
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.İslemler
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Restoran.RestoranIsmi)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.SubeIsmi)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Semt.Sehir.SehirAd)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Semt.SemtAd)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Telefon)
                                            </td>
                                            <td>
                                                @Html.ActionLink(" ", "Index", "SubeYorumlari", new { arama = item.SubeIsmi }, new { @class = "btn btn-sm btn-primary glyphicon glyphicon-comment" })
                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-7">
                            <span><b>@Resources.Kullanici.Home.Toplam @ViewBag.SonucSayisi @Resources.Kullanici.Home.Sonuc - </b>@Resources.Kullanici.Home.Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</span>
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, siralama = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                        </div>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>