YemekSepette/Areas/Admin/Controllers/SubeYorumlariController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekSepette.DAL;
using YemekSepette.Models;

namespace YemekSepette.Areas.Admin.Controllers
{
    public class SubeYorumlariController : AdminController
    {
        private YemekSepetteContext db = new YemekSepetteContext();

        // GET: Admin/SubeYorumlari
        public ActionResult Index(int? page, string currentFiler, string arama, string siralama)
        {
            if (arama != null)
            {
                page = 1;
            }
            else
            {
                arama = currentFiler;
            }
            ViewBag.CurrentFilter = arama;
            ViewBag.DateSortParam = siralama == "tarih_artan" ? "tarih_azalan" : "tarih_artan";
            ViewBag.CurrentSort = siralama;

            var yorumlar = db.SubeYorumlari.Include(x => x.Musteri).Include(x => x.Sube).OrderByDescending(x => x.Tarih).ToList();
            if (siralama == "tarih_artan")
            {
                yorumlar = db.SubeYorumlari.Include(x => x.Musteri).Include(x => x.Sube).OrderBy(x => x.Tarih).ToList();
            }

            if (!String.IsNullOrEmpty(arama))
            {
                yorumlar = yorumlar.Where(x => x.Sube.SubeIsmi.ToUpper().Contains(arama.ToUpper())
                || x.Tarih.ToString().Contains(arama.ToUpper()) || x.YorumIcerik.ToUpper().Contains(arama.ToUpper())
                ).ToList();
            }

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            ViewBag.SonucSayisi = yorumlar.Count();

            //var subeYorumlari = db.SubeYorumlari.Include(s => s.Musteri).Include(s => s.Sube);
            return View(yorumlar.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/SubeYorumlari/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubeYorum subeYorum = db.SubeYorumlari.Find(id);
            if (subeYorum == null)
            {
                return HttpNotFound();
            }
            return View(subeYorum);
        }

        // GET: Admin/SubeYorumlari/Create
        public ActionResult Create()
        {
            ViewBag.MusteriID = new SelectList(db.Musteriler, "MusteriID", "AdSoyad");
            ViewBag.SubeID = new SelectList(db.Subeler, "SubeID", "SubeIsmi");
            return View();
        }

        // POST: Admin/SubeYorumlari/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubeYorumID,MusteriID,SubeID,YorumIcerik,Tarih")] SubeYorum subeYorum)
        {
            if (ModelState.IsValid)
            {
                db.SubeYorumlari.Add(subeYorum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MusteriID = new SelectList(db.Musteriler, "MusteriID", "AdSoyad", subeYorum.MusteriID);
            ViewBag.SubeID = new SelectList(db.Subeler, "SubeID", "SubeIsmi", subeYorum.SubeID);
            return View(subeYorum);
        }

        // GET: Admin/SubeYorumlari/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubeYorum subeYorum = db.SubeYorumlari.Find(id);
            if (subeYorum == null)
            {
                return HttpNotFound();
            }
            ViewBag.MusteriID = new SelectList(db.Musteriler, "MusteriID", "AdSoyad", subeYorum.MusteriID);
            ViewBag.SubeID = new SelectList(db.Subeler, "SubeID", "SubeIsmi", subeYorum.SubeID);
            return View(subeYorum);
        }

        // POST: Admin/SubeYorumlari/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubeYorumID,MusteriID,SubeID,YorumIcerik,Tarih")] SubeYorum subeYorum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subeYorum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MusteriID = new SelectList(db.Musteriler, "MusteriID", "AdSoyad", subeYorum.MusteriID);
            ViewBag.SubeID = new SelectList(db.Subeler, "SubeID", "SubeIsmi", subeYorum.SubeID);
            return View(subeYorum);
        }

        // GET: Admin/SubeYorumlari/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubeYorum subeYorum = db.SubeYorumlari.Find(id);
            if (subeYorum == null)
            {
                return HttpNotFound();
            }
            return View(subeYorum);
        }

        // POST: Admin/SubeYorumlari/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SubeYorum subeYorum = db.SubeYorumlari.Find(id);
            db.SubeYorumlari.Remove(subeYorum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekSepette/Areas/Admin/Views/SubeYorumlari/Create.cshtml
@model YemekSepette.Models.SubeYorum

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SubeYorum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MusteriID, "MusteriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MusteriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MusteriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubeID, "SubeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YorumIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YorumIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YorumIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekSepette/Areas/Admin/Views/SubeYorumlari/Delete.cshtml
@model YemekSepette.Models.SubeYorum

@{
    ViewBag.Title = Resources.Kullanici.Home.YorumSil;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-sm-6">
        <div class="box box-danger box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.YorumSil</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">
                <h4>@Resources.Kullanici.Home.SilmeOnay<!--Are you sure you want to delete this?--></h4>
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-3">
                            <b>@Resources.Kullanici.Home.SubeIsmi: </b>
                        </div>
                        <div class="col-sm-9">
                            @Html.DisplayFor(model => model.Sube.SubeIsmi)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <b>@Resources.Kullanici.Home.Icerik: </b>
                        </div>
                        <div class="col-sm-9">
                            @Html.DisplayFor(model => model.YorumIcerik)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <b>@Resources.Kullanici.Home.Tarih: </b>
                        </div>
                        <div class="col-sm-9">
                            @Html.DisplayFor(model => model.Tarih)
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="box-footer">
                    @Html.ActionLink(Resources.Kullanici.Home.ListeyeGeriDon, "Index", new { }, new { @class = "btn btn-primary" })
                    <input type="submit" value="@Resources.Kullanici.Home.Sil" class="btn btn-danger pull-right" />
                </div>
            }
            <!-- /.box-footer -->

        </div>
    </div>
</div>

YemekSepette/Areas/Admin/Views/SubeYorumlari/Details.cshtml
@model YemekSepette.Models.SubeYorum

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SubeYorum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Musteri.AdSoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Musteri.AdSoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sube.SubeIsmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sube.SubeIsmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YorumIcerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YorumIcerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubeYorumID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

YemekSepette/Areas/Admin/Views/SubeYorumlari/Edit.cshtml
@model YemekSepette.Models.SubeYorum

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SubeYorum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubeYorumID)

        <div class="form-group">
            @Html.LabelFor(model => model.MusteriID, "MusteriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MusteriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MusteriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubeID, "SubeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YorumIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YorumIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YorumIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekSepette/Areas/Admin/Views/SubeYorumlari/Index.cshtml
@model PagedList.IPagedList<YemekSepette.Models.SubeYorum>
@using PagedList.Mvc;

@{
    ViewBag.Title = Resources.Kullanici.Home.SubeYorumlari;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-warning box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.SubeYorumlari</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            @using (Html.BeginForm("Index", "SubeYorumlari", FormMethod.Get))
                            {
                                <div class="input-group">
                                    @Html.TextBox("Arama", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                                    <div class="input-group-btn">
                                        <input type="submit" value="@Resources.Kullanici.Home.Ara" class="btn btn-danger" />
                                    </div>
                                    <!-- /btn-group -->

                                </div>
                            }
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                <thead>
                                    <tr role="row">
                                        <th>
                                            @Resources.Kullanici.Home.SubeIsmi
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.Icerik
                                        </th>
                                        <th>
                                            @Html.ActionLink(Resources.Kullanici.Home.Tarih, "Index", new { siralama = ViewBag.DateSortParam })
                                        </th>
                                        <th>
                                            @Resources.Kullanici.Home.İslemler
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Sube.SubeIsmi)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.YorumIcerik)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Tarih)
                                            </td>
                                            <td>
                                                @Html.ActionLink(" ", "Delete", new { id = item.SubeYorumID }, new { @class = "btn btn-sm btn-danger glyphicon glyphicon-trash" })
                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-7">
                            <span><b>@Resources.Kullanici.Home.Toplam @ViewBag.SonucSayisi @Resources.Kullanici.Home.Sonuc - </b>@Resources.Kullanici.Home.Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</span>
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, siralama = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                        </div>
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>