YemekSepette/Controllers/GoruslerinizController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YemekSepette.DAL;
using YemekSepette.Models;

namespace YemekSepette.Controllers
{
    public class GoruslerinizController : Controller
    {
        YemekSepetteContext db = new YemekSepetteContext();
        ApplicationDbContext applicationDbContext = new ApplicationDbContext();

        // GET: Gorusleriniz
        public ActionResult Index(int? page)
        {
            if (AuthenticationManager.User.Identity.IsAuthenticated)
            {
                var kullanici = applicationDbContext.Users.
                Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();

                var userStore = new UserStore<ApplicationUser>(applicationDbContext);
                var userManager = new UserManager<ApplicationUser>(userStore);
                if (userManager.IsInRole(kullanici.Id, "Kullanıcı") == false)
                {
                    bool adminRolundeMi = userManager.IsInRole(kullanici.Id, "Admin");
                    bool restoranRolundeMi = userManager.IsInRole(kullanici.Id, "Restoran");
                    bool subeRolundeMi = userManager.IsInRole(kullanici.Id, "Şube");
                    if (adminRolundeMi)
                    {
                        return Redirect("/Admin");
                    }
                    else if (restoranRolundeMi)
                    {
                        return Redirect("/RestoranPanel");
                    }
                    else if (subeRolundeMi)
                    {
                        return Redirect("/SubePanel");
                    }
                }

            }

            var gorusler = db.Gorusler.OrderByDescending(x => x.GorusTarih);
            ViewBag.GorusSayisi = gorusler.Count();
            ViewBag.GorusSayfasindaMiyiz = true;

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(gorusler.ToPagedList(pageNumber, pageSize));
        }

        [ChildActionOnly]
        public ActionResult _Gorusler()
        {
            var gorusler = db.Gorusler.OrderByDescending(x => x.GorusTarih);
            return View(gorusler);
        }

        [ChildActionOnly]
        public ActionResult _GorusBildir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult _GorusBildir(Gorus gorus)
        {
            if (ModelState.IsValid)
            {
                gorus.GorusTarih = DateTime.Now;
                db.Gorusler.Add(gorus);
                db.SaveChanges();
            }


            return RedirectToAction("Index");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}

YemekSepette/Views/Gorusleriniz/Index.cshtml
@model PagedList.IPagedList<YemekSepette.Models.Gorus>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = @Resources.Kullanici.Home.Gorusleriniz;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header" style="margin-top:0">
    <h3>@Resources.Kullanici.Home.HakkimizdaGorusleriniz</h3>
    <p>@Resources.Kullanici.Home.YapılanGoruslereGozatin</p>
</div>

<div class="panel panel-warning">
    <div class="panel-heading"><b>@Resources.Kullanici.Home.Gorusleriniz</b></div>
    <!-- List group -->
    <ul class="list-group">
        @{
            var i = 0;
        }
        @foreach (var item in Model)
        {
            i++;
            if (i > 5)
            {
                break;
            }
            <li class="list-group-item">
                <span class="col-sm-12" style="padding:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">@item.GorusIcerik</span>
                <div><small>@Html.DisplayFor(modelItem => item.GorusTarih)</small></div>
            </li>
        }
    </ul>
    <div class="panel-footer" style="background-color:#fbfbfb">
        <span>@Resources.Kullanici.Home.Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</span> - <span>@Resources.Kullanici.Home.Toplam <b>@ViewBag.GorusSayisi</b> @Resources.Kullanici.Home.GorusKucuk</span>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>

@{ Html.RenderAction("_GorusBildir", "Gorusleriniz");}

YemekSepette/Views/Gorusleriniz/_GorusBildir.cshtml
@model YemekSepette.Models.Gorus

@{
    Layout = null;
}

<div class="row col-sm-12" style="margin-top:0">
    <h3>@Resources.Kullanici.Home.GorusunuBildir</h3>
    <p>@Resources.Kullanici.Home.GorusunuHerkeslePaylas<p>
</div>

<div class="row col-sm-12">
    @if (Request.IsAuthenticated)
    {
    <!-- yorum gonder -->

        using (Html.BeginForm("_GorusBildir", "Gorusleriniz", FormMethod.Post))
        {
            Html.AntiForgeryToken();
            <form class="form-horizontal">
                <fieldset>

                    <legend></legend>

                    <div class="form-group">
                        <label for="textArea" class="col-lg-2 control-label">@Resources.Kullanici.Home.Gorus :</label>
                        <div class="col-lg-10">
                            @Html.TextAreaFor(model => model.GorusIcerik, new { @class = "form-control", @row = "3" })
                            <span class="help-block">@Resources.Kullanici.Home.HakaretUyariGorus</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">@Resources.Kullanici.Home.Gonder</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        }

    }
    else
    {
    <!-- giris yapilmamissa -->
        <div class="row">
            <div class="col-sm-12">
                <div class="bs-component">
                    <div class="alert alert-dismissible alert-warning">
                        <h4>@Resources.Kullanici.Home.Uyari</h4>
                        <p>@Resources.Kullanici.Home.GorusIcinGiris</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

YemekSepette/Views/Gorusleriniz/_Gorusler.cshtml
@model IEnumerable<YemekSepette.Models.Gorus>

@{
    Layout = null;
}
<div class="panel panel-warning">
    <div class="panel-heading"><b>@Resources.Kullanici.Home.Gorusleriniz</b></div>
    <!-- List group -->
    <ul class="list-group">
        @{
            var i = 0;
        }
        @foreach (var item in Model)
        {
            i++;
            if (i > 5)
            {
                break;
            }
            <li class="list-group-item">
                <span class="col-sm-12" style="padding:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">@item.GorusIcerik</span>
                <div><small>@Html.DisplayFor(modelItem => item.GorusTarih)</small></div>
            </li>
        }
    </ul>
    <div class="panel-footer">
        <span><a href="@Url.Action("Index", "Gorusleriniz", new { language = HttpContext.Current.Response.Cookies["dil"].Value })">@Resources.Kullanici.Home.TumGorusleriGor</a> <b>(@Model.Count() @Resources.Kullanici.Home.Gorus)</b></span>
    </div>
</div>