YemekSepette/Areas/SubePanel/Controllers/SubeUrunController.cs
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekSepette.Areas.SubePanel.Models;
using YemekSepette.DAL;
using YemekSepette.Models;

namespace YemekSepette.Areas.SubePanel.Controllers
{
    public class SubeUrunController : SubePanelController
    {
        ApplicationDbContext applicationDbContext = new ApplicationDbContext();
        private YemekSepetteContext db = new YemekSepetteContext();

        // GET: SubePanel/SubeUrun
        public ActionResult Index()
        {
            var kullanici = applicationDbContext.Users.Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
            var kullaniciBilgi = db.Subeler.Where(x => x.SubeID == kullanici.KullaniciTipId).First();
            var urunler = db.Urunler.Include(u => u.Menu).Where(x => kullaniciBilgi.SubeID == x.Menu.SubeID);
            return View(urunler.ToList());
        }
        IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        // GET: SubePanel/SubeUrun/Create
        public ActionResult Create()
        {
            var kullanici = applicationDbContext.Users.Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
            var kullaniciBilgi = db.Subeler.Where(x => x.SubeID == kullanici.KullaniciTipId).First();
            ViewBag.MenuID = new SelectList(db.Menuler.Where(x => x.SubeID == kullaniciBilgi.SubeID), "MenuID", "MenuIsmi");
            return View();
        }

        // POST: SubePanel/SubeUrun/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunID,MenuID,UrunIsmi,UrunIcerik,Fiyat")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Urunler.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var kullanici = applicationDbContext.Users.Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
            var kullaniciBilgi = db.Subeler.Where(x => x.SubeID == kullanici.KullaniciTipId).First();
            ViewBag.MenuID = new SelectList(db.Menuler.Where(x => x.SubeID == kullaniciBilgi.SubeID), "MenuID", "MenuIsmi", urun.MenuID);
            return View(urun);
        }

        // GET: SubePanel/SubeUrun/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urunler.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            var kullanici = applicationDbContext.Users.Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
            var kullaniciBilgi = db.Subeler.Where(x => x.SubeID == kullanici.KullaniciTipId).First();
            ViewBag.MenuID = new SelectList(db.Menuler.Where(x => x.SubeID == kullaniciBilgi.SubeID), "MenuID", "MenuIsmi", urun.MenuID);
            return View(urun);
        }

        // POST: SubePanel/SubeUrun/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunID,MenuID,UrunIsmi,UrunIcerik,Fiyat")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var kullanici = applicationDbContext.Users.Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
            var kullaniciBilgi = db.Subeler.Where(x => x.SubeID == kullanici.KullaniciTipId).First();
            ViewBag.MenuID = new SelectList(db.Menuler.Where(x => x.SubeID == kullaniciBilgi.SubeID), "MenuID", "MenuIsmi", urun.MenuID);

            return View(urun);
        }

        // GET: SubePanel/SubeUrun/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urunler.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: SubePanel/SubeUrun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var siparisler = db.Siparisler.Where(x => x.UrunID == id).ToList();
            siparisler.ForEach(x => db.Siparisler.Remove(x));
            Urun urun = db.Urunler.Find(id);
            db.Urunler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekSepette/Areas/SubePanel/Views/SubeUrun/Create.cshtml
@model YemekSepette.Models.Urun

@{
    ViewBag.Title = @Resources.Kullanici.Home.UrunEkle;
    Layout = "~/Areas/SubePanel/Views/Shared/_SubePanelLayout.cshtml";
}

<div class="row">
    <div class="col-sm-6">
        <div class="box box-success box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.UrunEkle</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="box-body">

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunIsmi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunIsmi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UrunIsmi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunIcerik, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UrunIcerik, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    @Html.ActionLink(@Resources.Kullanici.Home.GeriDon, "Index", new { }, new { @class = "btn btn-primary" })
                    <input type="submit" value=@Resources.Kullanici.Home.Kaydet class="btn btn-success pull-right" />
                </div>
            }
            <!-- /.box-footer -->

        </div>
    </div>
</div>

YemekSepette/Areas/SubePanel/Views/SubeUrun/Delete.cshtml
@model YemekSepette.Models.Urun

@{
    ViewBag.Title = @Resources.Kullanici.Home.UrunSil;
    Layout = "~/Areas/SubePanel/Views/Shared/_SubePanelLayout.cshtml";
}
<div class="row">
    <div class="col-sm-6">
        <div class="box box-danger box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.UrunSil</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">
                <h4>@Resources.Kullanici.Home.SilmeyeEminMisin</h4>
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-2">
                            <b>@Html.DisplayNameFor(model => model.Menu.MenuIsmi): </b>
                        </div>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.Menu.MenuIsmi)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            <b>@Html.DisplayNameFor(model => model.UrunIsmi): </b>
                        </div>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.UrunIsmi)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            <b>@Html.DisplayNameFor(model => model.UrunIcerik): </b>
                        </div>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.UrunIcerik)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            <b>@Html.DisplayNameFor(model => model.Fiyat): </b>
                        </div>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.Fiyat)
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()
                    <div class="box-footer">
                        @Html.ActionLink(@Resources.Kullanici.Home.GeriDon, "Index", new { }, new { @class = "btn btn-primary" })
                        <input type="submit" value=@Resources.Kullanici.Home.Sil class="btn btn-danger pull-right" />
                    </div>
                }
                <!-- /.box-footer -->

            </div>
        </div>
    </div>
</div>

YemekSepette/Areas/SubePanel/Views/SubeUrun/Edit.cshtml
@model YemekSepette.Models.Urun

@{
    ViewBag.Title = @Resources.Kullanici.Home.UrunDuzenle;
    Layout = "~/Areas/SubePanel/Views/Shared/_SubePanelLayout.cshtml";
}

<div class="row">
    <div class="col-sm-6">
        <div class="box box-primary box-solid">
            <div class="box-header">
                <h3 class="box-title">@Resources.Kullanici.Home.UrunDuzenle</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="box-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.UrunID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunIsmi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunIsmi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UrunIsmi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunIcerik, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UrunIcerik, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>


                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    @Html.ActionLink(@Resources.Kullanici.Home.GeriDon, "Index", new { }, new { @class = "btn btn-primary" })
                    <input type="submit" value=@Resources.Kullanici.Home.Kaydet class="btn btn-success pull-right" />
                </div>
            }
            <!-- /.box-footer -->

        </div>
    </div>
</div>

YemekSepette/Areas/SubePanel/Views/SubeUrun/Index.cshtml
@model IEnumerable<YemekSepette.Models.Urun>

@{
    ViewBag.Title = @Resources.Kullanici.Home.Urunler;
    Layout = "~/Areas/SubePanel/Views/Shared/_SubePanelLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="box box-warning box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">@Resources.Kullanici.Home.Urunler</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <a href="~/SubePanel/SubeUrun/Create" class="btn btn-primary">
                    <i class="glyphicon glyphicon-plus"></i> <b>@Resources.Kullanici.Home.UrunEkle</b>
                </a>
                <table class="table table-bordered" style="margin-top:10px">
                    <tbody>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Menu.MenuIsmi)</th>
                            <th>@Html.DisplayNameFor(model => model.UrunIsmi)</th>
                            <th>@Html.DisplayNameFor(model => model.UrunIcerik)</th>
                            <th>@Html.DisplayNameFor(model => model.Fiyat)</th>
                            <th>@Resources.Kullanici.Home.İslemler</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Menu.MenuIsmi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UrunIsmi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UrunIcerik)
                                </td>
                                <td>
                                    <span class="badge bg-green btn-block">@Html.DisplayFor(modelItem => item.Fiyat) TL</span>
                                </td>
                                <td>
                                    @Html.ActionLink(@Resources.Kullanici.Home.Duzenle, "Edit", "SubeUrun", new { id = item.UrunID }, new { @style = "font-weight:bold;", @class = "btn btn-warning glyphicon glyphicon-pencil" })
                                    @Html.ActionLink(@Resources.Kullanici.Home.Sil, "Delete", "SubeUrun", new { id = item.UrunID }, new { @style = "font-weight:bold;", @class = "btn btn-danger glyphicon glyphicon-trash" })

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
</div>